### ISSUE TITLE
Do you have any quantitive results on freenerf+sparsenerf method on LLFF or DTU?

### ISSUE THREAD

**Issue by hermosaaurora** [Wanggcong/FreeNeRF_plus_SparseNeRF#2]
as a comparable metric for users to evaluate whether their results are expected or not

**Comment by Wanggcong** [comment]
We compare freenerf vs. freenerf + sparsenerf in Table 6 of [our paper](https://arxiv.org/pdf/2303.16196.pdf). Please check it.

**Comment by hermosaaurora** [comment]
Thank you for your instant reply!
